# Generated by Django 4.1.5 on 2024-02-25 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CityInfos',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('cityname', models.CharField(db_column='CityName', max_length=255)),
                ('temperature', models.CharField(db_column='Temperature', max_length=255)),
                ('humidity', models.CharField(db_column='Humidity', max_length=255)),
                ('c_date', models.DateTimeField(blank=True, db_column='C_date', null=True)),
            ],
            options={
                'db_table': 'city_infos',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Musician',
        ),
    ]
